### ISSUE TITLE
"Cannot re-initialize CUDA in forked subprocess." error when processing input folder using preset

### ISSUE THREAD

**Issue by hundrix** [SUC-DriverOld/MSST-WebUI#32]
MSST Version: Use the latest version cloned from GitHub.
Environment: WSL2 under Windows 11,  Tesla P4 GPU
Operation: On the "Use preset" page, fill in "Input directory" and "Output directory", hit "Input folder separation" button.
Result: Please check the following log from console.

17:52:22.038 [INFO] [webui/preset.py:330] Starting preset inference process, use presets: clean single vocal.json
17:52:22.039 [INFO] [webui/preset.py:364] Step 1: Running inference using model_bs_roformer_ep_317_sdr_12.9755.ckpt
17:52:22.074 [INFO] [inference/msst_infer.py:72] Using device: cuda:0, device_ids: [0]
17:52:22.668 [ERROR] [webui/msst.py:204] Separation failed: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
Traceback (most recent call last):
  File "/home/wangxh/msst/MSST-WebUI/webui/msst.py", line 186, in run_inference
    separator = MSSeparator(
                ^^^^^^^^^^^^
  File "/home/wangxh/msst/MSST-WebUI/inference/msst_infer.py", line 74, in __init__
    self.model, self.config = self.load_model()
                              ^^^^^^^^^^^^^^^^^
  File "/home/wangxh/msst/MSST-WebUI/inference/msst_infer.py", line 106, in load_model
    model, config = get_model_from_config(self.model_type, self.config_path)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangxh/msst/MSST-WebUI/utils/utils.py", line 43, in get_model_from_config
    model = BSRoformer(
            ^^^^^^^^^^^
  File "<@beartype(modules.bs_roformer.bs_roformer.BSRoformer.__init__) at 0x7f1bc1bd8e00>", line 97, in __init__
  File "/home/wangxh/msst/MSST-WebUI/modules/bs_roformer/bs_roformer.py", line 392, in __init__
    Transformer(depth=time_transformer_depth, rotary_embed=time_rotary_embed, **transformer_kwargs)
  File "/home/wangxh/msst/MSST-WebUI/modules/bs_roformer/bs_roformer.py", line 201, in __init__
    attn = Attention(dim=dim, dim_head=dim_head, heads=heads, dropout=attn_dropout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangxh/msst/MSST-WebUI/modules/bs_roformer/bs_roformer.py", line 94, in __init__
    self.attend = Attend(flash=flash, dropout=dropout)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangxh/msst/MSST-WebUI/modules/bs_roformer/attend.py", line 62, in __init__
    device_properties = torch.cuda.get_device_properties(torch.device('cuda'))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangxh/miniconda3/envs/msst/lib/python3.11/site-packages/torch/cuda/__init__.py", line 444, in get_device_properties
    _lazy_init()  # will define _get_device_properties
    ^^^^^^^^^^^^
  File "/home/wangxh/miniconda3/envs/msst/lib/python3.11/site-packages/torch/cuda/__init__.py", line 279, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

Traceback (most recent call last):
  File "/home/wangxh/miniconda3/envs/msst/lib/python3.11/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangxh/miniconda3/envs/msst/lib/python3.11/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangxh/miniconda3/envs/msst/lib/python3.11/site-packages/gradio/blocks.py", line 1897, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangxh/miniconda3/envs/msst/lib/python3.11/site-packages/gradio/blocks.py", line 1483, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangxh/miniconda3/envs/msst/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangxh/miniconda3/envs/msst/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/wangxh/miniconda3/envs/msst/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 914, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangxh/miniconda3/envs/msst/lib/python3.11/site-packages/gradio/utils.py", line 816, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/home/wangxh/msst/MSST-WebUI/webui/preset.py", line 392, in preset_inference
    return i18n("处理失败: ") + result[1]
           ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str

**Comment by hundrix** [comment]
According to 'https://pytorch.org/docs/stable/notes/multiprocessing.html', torch.multiprocessing is a drop in replacement for Python’s multiprocessing module. I replace 
`import multiprocessing`
with 
`import torch.multiprocessing as multiprocessing`
in msst.py/preset.py/train.py/vr.py
This change serves as an interim solution.

**Comment by SUC-DriverOld** [comment]
see #30

**Comment by SUC-DriverOld** [comment]
Thank you for your suggested modifications!
