### ISSUE TITLE
求助：SOME 功能突然无法使用

### ISSUE THREAD

**Issue by YoMonNPC** [SUC-DriverOld/MSST-WebUI#33]
- [x] I have checked all the issues and the issue I raised has not been raised before.
- [x] I think the issue I raised is valuable rather than meaningless.

### Your operating environment
Windows 11 Pro AMD64; Python 3.10.11 (workenv); torch 2.2.0+cu121 (workenv); NVIDIA GeForce RTX 2070 SUPER, Studio Driver 566.14.

### How to reproduce
在 1.7 preview.1 曾正常使用，升级至 preview.3 后无法使用，回退至 preview.1 及 1.6.2 也无法使用。期间为更换版本卸载过电脑的 Python。

### Provide log here (optional)

<details> 
    <summary>Show</summary> 

```Log
02:19:28.770 [INFO] [webUI.py:136] 正在启动WebUI, 请稍等...
02:19:28.771 [INFO] [webUI.py:137] 若启动失败, 请尝试以管理员身份运行此程序
02:19:28.771 [WARNING] [webUI.py:138] WebUI运行过程中请勿关闭此窗口!
02:19:33.382 [INFO] [webUI.py:153] 检测到CUDA, 设备信息: {'cuda0': '0: NVIDIA GeForce RTX 2070 SUPER'}
02:19:33.382 [INFO] [webUI.py:164] WebUI Version: 1.7 preview.3, System: Windows, Machine: AMD64
02:19:33.384 [INFO] [webui\utils.py:68] Console log level set to [32mINFO[0m
02:19:33.384 [DEBUG] [D:\MSST WebUI\webUI.py:58] Starting WebUI setup
02:19:33.392 [DEBUG] [D:\MSST WebUI\webUI.py:65] Loading WebUI config: {'version': '1.7 preview.3', 'inference': {'model_type': None, 'selected_model': None, 'input_dir': None, 'store_dir': None, 'device': None, 'output_format': 'wav', 'force_cpu': False, 'instrumental': None, 'use_tta': False, 'preset': None, 'preset_use_tta': False, 'extra_output_dir': False, 'vr_select_model': None, 'vr_window_size': 512, 'vr_aggression': 5, 'vr_batch_size': 2, 'vr_primary_stem_only': False, 'vr_secondary_stem_only': False, 'vr_post_process_threshold': 0.2, 'vr_invert_spect': False, 'vr_enable_tta': False, 'vr_high_end_process': False, 'vr_enable_post_process': False}, 'tools': {'store_dir': None, 'output_format': 'wav', 'sample_rate': 44100, 'channels': 2, 'wav_bit_depth': 'PCM-16', 'flac_bit_depth': '16-bit', 'mp3_bit_rate': '320k', 'ogg_bit_rate': '320k', 'merge_audio_input': None, 'ensemble_type': None}, 'training': {'model_type': None, 'config_path': None, 'dataset_type': None, 'dataset_path': None, 'valid_path': None, 'num_workers': 0, 'device': None, 'seed': 0, 'pin_memory': False, 'use_multistft_loss': False, 'use_mse_loss': False, 'use_l1_loss': False, 'accelerate': False, 'pre_valid': False, 'metrics': None, 'metrics_scheduler': None, 'results_path': None}, 'settings': {'uvr_model_dir': 'pretrain/VR_Models', 'port': 0, 'language': 'Auto', 'download_link': 'Auto', 'local_link': False, 'share_link': False, 'auto_clean_cache': False, 'debug': False, 'theme': 'theme_blue.json'}}
02:19:33.393 [DEBUG] [D:\MSST WebUI\webUI.py:103] Set HF_HOME to: D:\MSST WebUI\pretrain
02:19:33.393 [DEBUG] [D:\MSST WebUI\webUI.py:104] Set HF_ENDPOINT to: https://hf-mirror.com
02:19:33.393 [DEBUG] [D:\MSST WebUI\webUI.py:105] Set ffmpeg PATH to: D:\MSST WebUI\ffmpeg\bin
02:19:33.393 [DEBUG] [D:\MSST WebUI\webUI.py:106] Set GRADIO_TEMP_DIR to: D:\MSST WebUI\cache
02:19:33.393 [DEBUG] [D:\MSST WebUI\webUI.py:184] Launching WebUI with parameters: server_name=None, server_port=None, share=False
02:20:04.280 [INFO] [webui\tools.py:169] Run SOME inference with command: .\workenv\python.exe tools/SOME/infer.py --model "tools/SOME_weights/model_steps_64000_simplified.ckpt" --wav "D:\MSST WebUI\cache\191bb24206d9d6a3d0b7be945f6722d970e6d1d2\###.wav" --midi "results/###.mid" --tempo 122
02:20:09.536 [ERROR] [webui\tools.py:176] Fail to run SOME inference. Error: Command '.\workenv\python.exe tools/SOME/infer.py --model "tools/SOME_weights/model_steps_64000_simplified.ckpt" --wav "D:\MSST WebUI\cache\191bb24206d9d6a3d0b7be945f6722d970e6d1d2\###.wav" --midi "results/###.mid" --tempo 122' returned non-zero exit status 1.
Traceback (most recent call last):
  File "D:\MSST WebUI\webui\tools.py", line 172, in some_inference
    subprocess.run(command, shell=False, check=True)
  File "subprocess.py", line 526, in run
subprocess.CalledProcessError: Command '.\workenv\python.exe tools/SOME/infer.py --model "tools/SOME_weights/model_steps_64000_simplified.ckpt" --wav "D:\MSST WebUI\cache\191bb24206d9d6a3d0b7be945f6722d970e6d1d2\###.wav" --midi "results/###.mid" --tempo 122' returned non-zero exit status 1.
```

</details>

**Comment by SUC-DriverOld** [comment]
感谢你的反馈！我已定位到问题所在，你可以更新至最新源码来修复此问题，或者前往tools/SOME_weights文件夹，打开config.yaml，修改第50行配置文件内容如下：
```
model_cls: tools.SOME.modules.model.Gmidi_conform.midi_conforms
```
修改完成后请重启webUI重试。如果还有问题，欢迎反馈！
