### ISSUE TITLE
两个包都安装了，杀毒关了，还是好多报错，求指导

### ISSUE THREAD

**Issue by lllrocky** [SUC-DriverOld/MSST-WebUI#44]
Traceback (most recent call last):
  File "C:\Program Files\MSST WebUI\workenv\Lib\site-packages\llvmlite\binding\ffi.py", line 136, in __getattr__
    return self._fntab[name]
KeyError: 'LLVMPY_AddSymbol'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\MSST WebUI\workenv\Lib\site-packages\llvmlite\binding\ffi.py", line 117, in _load_lib
    self._lib_handle = ctypes.CDLL(str(lib_path))
  File "ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'C:\Program Files\MSST WebUI\workenv\Lib\site-packages\llvmlite\binding\llvmlite.dll' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\94588\AppData\Local\Temp\8b5e09d8-ff2a-58bc-4195-59302ef0ac75.tmp", line 11, in <module>
    import librosa
  File "C:\Program Files\MSST WebUI\workenv\Lib\site-packages\librosa\__init__.py", line 209, in <module>
    from . import core
  File "C:\Program Files\MSST WebUI\workenv\Lib\site-packages\librosa\core\__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "C:\Program Files\MSST WebUI\workenv\Lib\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import notation
  File "C:\Program Files\MSST WebUI\workenv\Lib\site-packages\librosa\core\notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "C:\Program Files\MSST WebUI\workenv\Lib\site-packages\librosa\util\__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "C:\Program Files\MSST WebUI\workenv\Lib\site-packages\librosa\util\utils.py", line 9, in <module>
    import numba
  File "C:\Program Files\MSST WebUI\workenv\Lib\site-packages\numba\__init__.py", line 73, in <module>
    from numba.core import config
  File "C:\Program Files\MSST WebUI\workenv\Lib\site-packages\numba\core\config.py", line 17, in <module>
    import llvmlite.binding as ll
  File "C:\Program Files\MSST WebUI\workenv\Lib\site-packages\llvmlite\binding\__init__.py", line 4, in <module>
    from .dylib import *
  File "C:\Program Files\MSST WebUI\workenv\Lib\site-packages\llvmlite\binding\dylib.py", line 36, in <module>
    ffi.lib.LLVMPY_AddSymbol.argtypes = [
  File "C:\Program Files\MSST WebUI\workenv\Lib\site-packages\llvmlite\binding\ffi.py", line 139, in __getattr__
    cfn = getattr(self._lib, name)
  File "C:\Program Files\MSST WebUI\workenv\Lib\site-packages\llvmlite\binding\ffi.py", line 131, in _lib
    self._load_lib()
  File "C:\Program Files\MSST WebUI\workenv\Lib\site-packages\llvmlite\binding\ffi.py", line 125, in _load_lib
    raise OSError("Could not find/load shared object file") from e
OSError: Could not find/load shared object file
![批注 2024-12-16 074751](https://github.com/user-attachments/assets/dd2ddd47-9276-42e6-bed2-9f32919377ff)

**Comment by SUC-DriverOld** [comment]
首先检查是否存在'C:\Program Files\MSST WebUI\workenv\Lib\site-packages\llvmlite\binding\llvmlite.dll'这个文件，如果不存在，请尝试重新安装整合包，如果存在，则

应该是你的系统原因导致的，最好的解决方法是：从源码手动配置。其次，尝试使用以下命令卸载numba和llvmlite，然后重新安装。

```bash
working/python.exe -m pip uninstall numba llvmlite -y
working/python.exe -m pip install numba llvmlite
```

若在安装过程中出现编译失败的保存，需要安装visual studio 2022，并勾选使用C++的桌面开发，然后安装。安装完成后重试上面的步骤。

也可以参考下面的文章：
https://stackoverflow.com/questions/64541502/oserror-could-not-load-shared-object-file-llvmlite-dll-shap-related-what-cou
